const airports = [
  { value: 'MAD', label: 'מדריד (MAD)' },
  { value: 'CDG', label: 'פריז שארל דה גול (CDG)' },
  { value: 'LHR', label: 'לונדון היתרו (LHR)' },
  { value: 'JFK', label: 'ניו יורק קנדי (JFK)' },
  { value: 'SFO', label: 'סן פרנסיסקו (SFO)' },
  { value: 'IST', label: 'איסטנבול (IST)' },
  { value: 'FRA', label: 'פרנקפורט (FRA)' },
  { value: 'AMS', label: 'אמסטרדם (AMS)' },
  { value: 'BCN', label: 'ברצלונה (BCN)' },
  { value: 'FCO', label: 'רומא פיומיצ׳ינו (FCO)' },
  { value: 'MUC', label: 'מינכן (MUC)' },
  { value: 'ATH', label: 'אתונה (ATH)' },
  { value: 'CPH', label: 'קופנהגן (CPH)' },
  { value: 'DXB', label: 'דובאי (DXB)' },

  // שדות תעופה נוספים
  { value: 'TLV', label: 'תל אביב בן גוריון (TLV)' },
  { value: 'LGW', label: 'לונדון גטוויק (LGW)' },
  { value: 'ORY', label: 'פריז אורלי (ORY)' },
  { value: 'EWR', label: 'ניוארק (EWR)' },
  { value: 'BOS', label: 'בוסטון (BOS)' },
  { value: 'LAX', label: 'לוס אנג׳לס (LAX)' },
  { value: 'YYZ', label: 'טורונטו (YYZ)' },
  { value: 'ZRH', label: 'ציריך (ZRH)' },
  { value: 'VIE', label: 'וינה (VIE)' },
  { value: 'BRU', label: 'בריסל (BRU)' },
  { value: 'OSL', label: 'אוסלו (OSL)' },
  { value: 'ARN', label: 'שטוקהולם (ARN)' },
  { value: 'HEL', label: 'הלסינקי (HEL)' },
  { value: 'BKK', label: 'בנגקוק (BKK)' },
  { value: 'HKG', label: 'הונג קונג (HKG)' },
  { value: 'SIN', label: 'סינגפור (SIN)' },
  { value: 'NRT', label: 'טוקיו נריטה (NRT)' },
  { value: 'HND', label: 'טוקיו האנדה (HND)' },
  { value: 'ICN', label: 'סיאול (ICN)' },
  { value: 'SYD', label: 'סידני (SYD)' },
  { value: 'MEL', label: 'מלבורן (MEL)' },
  { value: 'GRU', label: 'סאו פאולו (GRU)' },
  { value: 'GIG', label: 'ריו דה ז׳נרו (GIG)' },
  { value: 'MEX', label: 'מקסיקו סיטי (MEX)' },
  { value: 'CUN', label: 'קנקון (CUN)' },
  { value: 'JNB', label: 'יוהנסבורג (JNB)' },
  { value: 'CPT', label: 'קייפטאון (CPT)' },

  // המשך שדות תעופה נפוצים נוספים
  { value: 'DUB', label: 'דבלין (DUB)' },
  { value: 'LIS', label: 'ליסבון (LIS)' },
  { value: 'PRG', label: 'פראג (PRG)' },
  { value: 'BUD', label: 'בודפשט (BUD)' },
  { value: 'WAW', label: 'ורשה (WAW)' },
  { value: 'KRK', label: 'קרקוב (KRK)' },
  { value: 'ZAG', label: 'זאגרב (ZAG)' },
  { value: 'OTP', label: 'בוקרשט (OTP)' },
  { value: 'SOF', label: 'סופיה (SOF)' },
  { value: 'BEG', label: 'בלגרד (BEG)' },
  { value: 'KEF', label: 'רייקיאוויק (KEF)' },

  // הוסף שדות תעופה נוספים לפי הצורך להשלמת 200 שדות תעופה
];

export default airports;
