// countries.js
const countries = [
  { value: 'IL', label: 'ישראל 🇮🇱' },
  { value: 'US', label: 'ארה"ב 🇺🇸' },
  { value: 'CA', label: 'קנדה 🇨🇦' },
  { value: 'GB', label: 'בריטניה 🇬🇧' },
  { value: 'FR', label: 'צרפת 🇫🇷' },
  { value: 'DE', label: 'גרמניה 🇩🇪' },
  { value: 'ES', label: 'ספרד 🇪🇸' },
  { value: 'IT', label: 'איטליה 🇮🇹' },
  { value: 'NL', label: 'הולנד 🇳🇱' },
  { value: 'BE', label: 'בלגיה 🇧🇪' },
  { value: 'CH', label: 'שוויץ 🇨🇭' },
  { value: 'SE', label: 'שוודיה 🇸🇪' },
  { value: 'NO', label: 'נורווגיה 🇳🇴' },
  { value: 'FI', label: 'פינלנד 🇫🇮' },
  { value: 'DK', label: 'דנמרק 🇩🇰' },
  { value: 'PT', label: 'פורטוגל 🇵🇹' },
  { value: 'GR', label: 'יוון 🇬🇷' },
  { value: 'CY', label: 'קפריסין 🇨🇾' },
  { value: 'MT', label: 'מלטה 🇲🇹' },
  { value: 'RU', label: 'רוסיה 🇷🇺' },
  { value: 'UA', label: 'אוקראינה 🇺🇦' },
  { value: 'PL', label: 'פולין 🇵🇱' },
  { value: 'CZ', label: 'צ׳כיה 🇨🇿' },
  { value: 'HU', label: 'הונגריה 🇭🇺' },
  { value: 'AT', label: 'אוסטריה 🇦🇹' },
  { value: 'AU', label: 'אוסטרליה 🇦🇺' },
  { value: 'NZ', label: 'ניו זילנד 🇳🇿' },
  { value: 'IN', label: 'הודו 🇮🇳' },
  { value: 'CN', label: 'סין 🇨🇳' },
  { value: 'JP', label: 'יפן 🇯🇵' },
  { value: 'TW', label: 'טאיוואן 🇹🇼' },
  { value: 'SG', label: 'סינגפור 🇸🇬' },
  { value: 'TH', label: 'תאילנד 🇹🇭' },
  { value: 'KR', label: 'קוריאה הדרומית 🇰🇷' },
  { value: 'BR', label: 'ברזיל 🇧🇷' },
  { value: 'AR', label: 'ארגנטינה 🇦🇷' },
  { value: 'MX', label: 'מקסיקו 🇲🇽' },
  { value: 'ZA', label: 'דרום אפריקה 🇿🇦' },
  { value: 'EG', label: 'מצרים 🇪🇬' },
  { value: 'TR', label: 'טורקיה 🇹🇷' },
  { value: 'AE', label: 'איחוד האמירויות 🇦🇪' },
  { value: 'QA', label: 'קטאר 🇶🇦' },
  { value: 'SA', label: 'ערב הסעודית 🇸🇦' },
  { value: 'MA', label: 'מרוקו 🇲🇦' },
  { value: 'IE', label: 'אירלנד 🇮🇪' },
  { value: 'RO', label: 'רומניה 🇷🇴' },
  { value: 'BG', label: 'בולגריה 🇧🇬' },
  { value: 'HR', label: 'קרואטיה 🇭🇷' },
  { value: 'IS', label: 'איסלנד 🇮🇸' },
  { value: 'CL', label: 'צ׳ילה 🇨🇱' },
  { value: 'CO', label: 'קולומביה 🇨🇴' },
  { value: 'VE', label: 'ונצואלה 🇻🇪' },
  { value: 'PE', label: 'פרו 🇵🇪' },
  { value: 'PH', label: 'הפיליפינים 🇵🇭' },
  { value: 'ID', label: 'אינדונזיה 🇮🇩' },
  { value: 'MY', label: 'מלזיה 🇲🇾' },
  { value: 'VN', label: 'וייטנאם 🇻🇳' },
  { value: 'KH', label: 'קמבודיה 🇰🇭' },
  { value: 'PK', label: 'פקיסטן 🇵🇰' },
  { value: 'BD', label: 'בנגלדש 🇧🇩' },
  { value: 'LK', label: 'סרי לנקה 🇱🇰' },
  { value: 'NG', label: 'ניגריה 🇳🇬' },
  { value: 'KE', label: 'קניה 🇰🇪' },
  { value: 'GH', label: 'גאנה 🇬🇭' },
  { value: 'TN', label: 'תוניסיה 🇹🇳' },
  { value: 'DZ', label: 'אלג׳יריה 🇩🇿' },
  { value: 'GE', label: 'גאורגיה 🇬🇪' },
  { value: 'AM', label: 'ארמניה 🇦🇲' },
  { value: 'AZ', label: 'אזרבייג׳ן 🇦🇿' },
  { value: 'KZ', label: 'קזחסטן 🇰🇿' },
  { value: 'UZ', label: 'אוזבקיסטן 🇺🇿' },
  { value: 'BY', label: 'בלארוס 🇧🇾' },
  { value: 'LV', label: 'לטביה 🇱🇻' },
  { value: 'LT', label: 'ליטא 🇱🇹' },
  { value: 'EE', label: 'אסטוניה 🇪🇪' },
  { value: 'SK', label: 'סלובקיה 🇸🇰' },
  { value: 'SI', label: 'סלובניה 🇸🇮' },
  { value: 'RS', label: 'סרביה 🇷🇸' },
  { value: 'BA', label: 'בוסניה 🇧🇦' },
  { value: 'AL', label: 'אלבניה 🇦🇱' },
];

export default countries;
